/**
 * Catalog Data - 465 Parts Library organized into 11 categories
 * Production-ready parts for manufacturing
 */

export type CategoryId =
  | 'profiles-frames'
  | 'plates-sheets'
  | 'fasteners'
  | 'bearings-shafts'
  | 'power-transmission'
  | 'enclosures'
  | 'fluid-process'
  | 'thermal'
  | 'mobility'
  | 'electrical-iot'
  | 'tooling';

export interface CatalogCategory {
  id: CategoryId;
  name: string;
  icon: string;
  description: string;
  unlocks: string;
  count: number;
}

export interface CatalogPart {
  id: string;
  name: string;
  category: CategoryId;
  categoryIcon?: string;
  description: string;
  unlocksText: string;
  material: string;
  process?: string;
  finish?: string;
  basePrice: number;
  leadTime?: string;
  leadTimeDays?: number;
  manufacturability?: number;
  thumbnail?: string;
  qty?: number;
  specs?: {
    width?: number;
    height?: number;
    length?: number;
    diameter?: number;
    wallThickness?: number;
    sideLength?: number;
    unitLength?: number;
    threadSize?: string;
    [key: string]: number | string | undefined;
  };
  variants?: Array<{
    id: string;
    name: string;
    specs: Record<string, number | string>;
    priceMultiplier: number;
  }>;
  materials?: Array<{ name: string; priceMultiplier: number }>;
  finishes?: string[];
}

export const CATALOG_CATEGORIES: CatalogCategory[] = [
  {
    id: 'profiles-frames',
    name: 'Structural Profiles & Frames',
    icon: '🏗️',
    description: 'High-reuse backbone of all machines',
    unlocks: 'Frames, racks, enclosures, carts, machines',
    count: 80,
  },
  {
    id: 'plates-sheets',
    name: 'Plates, Panels & Sheets',
    icon: '📋',
    description: 'Everything mounts on these',
    unlocks: 'Assembly surfaces, structural support, aesthetics',
    count: 60,
  },
  {
    id: 'fasteners',
    name: 'Fasteners & Joining',
    icon: '🔩',
    description: 'Absolutely mandatory. Highest reorder frequency',
    unlocks: 'Assembly, structural integrity',
    count: 70,
  },
  {
    id: 'bearings-shafts',
    name: 'Bearings, Shafts & Motion Core',
    icon: '⚙️',
    description: 'Enables all rotating systems',
    unlocks: 'Rotating equipment, linear motion systems',
    count: 50,
  },
  {
    id: 'power-transmission',
    name: 'Power Transmission',
    icon: '🔧',
    description: 'Motion scaling without electronics',
    unlocks: 'Speed/torque adjustment, mechanical advantage',
    count: 45,
  },
  {
    id: 'enclosures',
    name: 'Enclosures & Casings',
    icon: '📦',
    description: 'Critical for productization',
    unlocks: 'Finished products, safety, aesthetics',
    count: 40,
  },
  {
    id: 'fluid-process',
    name: 'Fluid & Process Hardware',
    icon: '💧',
    description: 'Unlocks agro-processing, water, oil, health',
    unlocks: 'Fluid systems, agricultural equipment, water processing',
    count: 45,
  },
  {
    id: 'thermal',
    name: 'Thermal & Energy Components',
    icon: '🔥',
    description: 'Low-tech but powerful',
    unlocks: 'Thermal management, furnaces, ovens, heating systems',
    count: 30,
  },
  {
    id: 'mobility',
    name: 'Mobility & Handling',
    icon: '🛞',
    description: 'Everything must move',
    unlocks: 'Mobile equipment, carts, conveyors',
    count: 30,
  },
  {
    id: 'electrical-iot',
    name: 'Electrical & IoT Mechanical Interfaces',
    icon: '⚡',
    description: 'Hardware meets electronics',
    unlocks: 'Electromechanical integration, automation',
    count: 25,
  },
  {
    id: 'tooling',
    name: 'Tooling & Jigs',
    icon: '🔨',
    description: 'These improve the platform itself',
    unlocks: 'Faster iteration, precision manufacturing, quality improvement',
    count: 25,
  },
];

// ===========================
// CATEGORY 1: STRUCTURAL PROFILES & FRAMES (80 parts)
// ===========================

const structuralProfiles: CatalogPart[] = [
  // Square Hollow Sections (10)
  {
    id: 'shs-001',
    name: 'Square Hollow Section 40x40x3mm',
    category: 'profiles-frames',
    description:
      '40mm square tube, 3mm wall thickness, versatile structural element',
    unlocksText: 'Frames, racks, enclosures, carts',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 2500,
    leadTime: '3 days',
    leadTimeDays: 3,
    manufacturability: 98,
    specs: { sideLength: 40, wallThickness: 3, unitLength: 1000 },
    variants: [
      {
        id: 'shs-001-1500',
        name: '1500mm length',
        specs: { unitLength: 1500 },
        priceMultiplier: 1.3,
      },
      {
        id: 'shs-001-2000',
        name: '2000mm length',
        specs: { unitLength: 2000 },
        priceMultiplier: 1.5,
      },
    ],
    finishes: ['Raw', 'Powder Coat', 'Paint'],
  },
  {
    id: 'shs-002',
    name: 'Square Hollow Section 50x50x4mm',
    category: 'profiles-frames',
    description: '50mm square tube, 4mm wall, heavy-duty applications',
    unlocksText: 'Frames, racks, enclosures, carts',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 3200,
    leadTime: '3 days',
    leadTimeDays: 3,
    manufacturability: 98,
    specs: { sideLength: 50, wallThickness: 4, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint'],
  },
  {
    id: 'shs-003',
    name: 'Square Hollow Section 60x60x5mm',
    category: 'profiles-frames',
    description: '60mm square tube, 5mm wall, industrial strength',
    unlocksText: 'Frames, racks, enclosures, carts',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 4500,
    leadTime: '3 days',
    leadTimeDays: 3,
    manufacturability: 98,
    specs: { sideLength: 60, wallThickness: 5, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint', 'Galvanized'],
  },
  {
    id: 'shs-004',
    name: 'Square Hollow Section 80x80x6mm',
    category: 'profiles-frames',
    description: '80mm square tube, 6mm wall, maximum strength',
    unlocksText: 'Frames, racks, enclosures, carts',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 6800,
    leadTime: '3 days',
    leadTimeDays: 3,
    manufacturability: 98,
    specs: { sideLength: 80, wallThickness: 6, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint', 'Galvanized'],
  },
  {
    id: 'shs-005',
    name: 'Square Hollow Section 25x25x2mm',
    category: 'profiles-frames',
    description: '25mm square tube, 2mm wall, light-duty frames',
    unlocksText: 'Frames, racks, enclosures, carts',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 1500,
    leadTime: '3 days',
    leadTimeDays: 3,
    manufacturability: 98,
    specs: { sideLength: 25, wallThickness: 2, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint'],
  },
  {
    id: 'shs-006',
    name: 'Square Hollow Section 30x30x2.5mm',
    category: 'profiles-frames',
    description: '30mm square tube, 2.5mm wall, compact structural',
    unlocksText: 'Frames, racks, enclosures, carts',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 1800,
    leadTime: '3 days',
    leadTimeDays: 3,
    manufacturability: 98,
    specs: { sideLength: 30, wallThickness: 2.5, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint'],
  },
  {
    id: 'shs-007',
    name: 'Square Hollow Section 70x70x5mm',
    category: 'profiles-frames',
    description: '70mm square tube, 5mm wall, robust structure',
    unlocksText: 'Frames, racks, enclosures, carts',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 5500,
    leadTime: '3 days',
    leadTimeDays: 3,
    manufacturability: 98,
    specs: { sideLength: 70, wallThickness: 5, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint', 'Galvanized'],
  },
  {
    id: 'shs-008',
    name: 'Square Hollow Section 100x100x8mm',
    category: 'profiles-frames',
    description: '100mm square tube, 8mm wall, extra heavy-duty',
    unlocksText: 'Frames, racks, enclosures, carts',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 9500,
    leadTime: '3 days',
    leadTimeDays: 3,
    manufacturability: 98,
    specs: { sideLength: 100, wallThickness: 8, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint', 'Galvanized'],
  },
  {
    id: 'shs-009',
    name: 'Square Hollow Section 20x20x2mm',
    category: 'profiles-frames',
    description: '20mm square tube, 2mm wall, ultra-light frames',
    unlocksText: 'Frames, racks, enclosures, carts',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 1200,
    leadTime: '3 days',
    leadTimeDays: 3,
    manufacturability: 98,
    specs: { sideLength: 20, wallThickness: 2, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint'],
  },
  {
    id: 'shs-010',
    name: 'Square Hollow Section 120x120x10mm',
    category: 'profiles-frames',
    description: '120mm square tube, 10mm wall, massive structural load',
    unlocksText: 'Frames, racks, enclosures, carts',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 14000,
    leadTime: '4 days',
    leadTimeDays: 4,
    manufacturability: 98,
    specs: { sideLength: 120, wallThickness: 10, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint', 'Galvanized'],
  },

  // Rectangular Hollow Sections (10)
  {
    id: 'rhs-001',
    name: 'Rectangular Hollow Section 40x20x2mm',
    category: 'profiles-frames',
    description: '40x20mm rectangular tube, 2mm wall',
    unlocksText: 'Frames, racks, enclosures, carts',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 1800,
    leadTime: '3 days',
    leadTimeDays: 3,
    manufacturability: 97,
    specs: { width: 40, height: 20, wallThickness: 2, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint'],
  },
  {
    id: 'rhs-002',
    name: 'Rectangular Hollow Section 50x25x3mm',
    category: 'profiles-frames',
    description: '50x25mm rectangular tube, 3mm wall',
    unlocksText: 'Frames, racks, enclosures, carts',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 2300,
    leadTime: '3 days',
    leadTimeDays: 3,
    manufacturability: 97,
    specs: { width: 50, height: 25, wallThickness: 3, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint'],
  },
  {
    id: 'rhs-003',
    name: 'Rectangular Hollow Section 60x40x4mm',
    category: 'profiles-frames',
    description: '60x40mm rectangular tube, 4mm wall',
    unlocksText: 'Frames, racks, enclosures, carts',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 3500,
    leadTime: '3 days',
    leadTimeDays: 3,
    manufacturability: 97,
    specs: { width: 60, height: 40, wallThickness: 4, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint'],
  },
  {
    id: 'rhs-004',
    name: 'Rectangular Hollow Section 80x40x5mm',
    category: 'profiles-frames',
    description: '80x40mm rectangular tube, 5mm wall',
    unlocksText: 'Frames, racks, enclosures, carts',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 4800,
    leadTime: '3 days',
    leadTimeDays: 3,
    manufacturability: 97,
    specs: { width: 80, height: 40, wallThickness: 5, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint', 'Galvanized'],
  },
  {
    id: 'rhs-005',
    name: 'Rectangular Hollow Section 100x50x5mm',
    category: 'profiles-frames',
    description: '100x50mm rectangular tube, 5mm wall',
    unlocksText: 'Frames, racks, enclosures, carts',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 5800,
    leadTime: '3 days',
    leadTimeDays: 3,
    manufacturability: 97,
    specs: { width: 100, height: 50, wallThickness: 5, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint', 'Galvanized'],
  },
  {
    id: 'rhs-006',
    name: 'Rectangular Hollow Section 120x60x6mm',
    category: 'profiles-frames',
    description: '120x60mm rectangular tube, 6mm wall',
    unlocksText: 'Frames, racks, enclosures, carts',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 7500,
    leadTime: '4 days',
    leadTimeDays: 4,
    manufacturability: 97,
    specs: { width: 120, height: 60, wallThickness: 6, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint', 'Galvanized'],
  },
  {
    id: 'rhs-007',
    name: 'Rectangular Hollow Section 30x20x2mm',
    category: 'profiles-frames',
    description: '30x20mm rectangular tube, 2mm wall',
    unlocksText: 'Frames, racks, enclosures, carts',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 1500,
    leadTime: '3 days',
    leadTimeDays: 3,
    manufacturability: 97,
    specs: { width: 30, height: 20, wallThickness: 2, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint'],
  },
  {
    id: 'rhs-008',
    name: 'Rectangular Hollow Section 150x100x8mm',
    category: 'profiles-frames',
    description: '150x100mm rectangular tube, 8mm wall',
    unlocksText: 'Frames, racks, enclosures, carts',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 11000,
    leadTime: '4 days',
    leadTimeDays: 4,
    manufacturability: 97,
    specs: { width: 150, height: 100, wallThickness: 8, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint', 'Galvanized'],
  },
  {
    id: 'rhs-009',
    name: 'Rectangular Hollow Section 70x50x4mm',
    category: 'profiles-frames',
    description: '70x50mm rectangular tube, 4mm wall',
    unlocksText: 'Frames, racks, enclosures, carts',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 4200,
    leadTime: '3 days',
    leadTimeDays: 3,
    manufacturability: 97,
    specs: { width: 70, height: 50, wallThickness: 4, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint'],
  },
  {
    id: 'rhs-010',
    name: 'Rectangular Hollow Section 90x60x5mm',
    category: 'profiles-frames',
    description: '90x60mm rectangular tube, 5mm wall',
    unlocksText: 'Frames, racks, enclosures, carts',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 5200,
    leadTime: '3 days',
    leadTimeDays: 3,
    manufacturability: 97,
    specs: { width: 90, height: 60, wallThickness: 5, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint', 'Galvanized'],
  },

  // Angle Irons (10)
  {
    id: 'ang-001',
    name: 'Angle Iron 40x40x5mm',
    category: 'profiles-frames',
    description: 'Equal angle 40x40mm, 5mm thickness',
    unlocksText: 'Frames, brackets, reinforcement',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 2200,
    leadTime: '2 days',
    leadTimeDays: 2,
    manufacturability: 98,
    specs: { width: 40, height: 40, wallThickness: 5, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint', 'Galvanized'],
  },
  {
    id: 'ang-002',
    name: 'Angle Iron 50x50x6mm',
    category: 'profiles-frames',
    description: 'Equal angle 50x50mm, 6mm thickness',
    unlocksText: 'Frames, brackets, reinforcement',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 2800,
    leadTime: '2 days',
    leadTimeDays: 2,
    manufacturability: 98,
    specs: { width: 50, height: 50, wallThickness: 6, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint', 'Galvanized'],
  },
  {
    id: 'ang-003',
    name: 'Angle Iron 60x60x6mm',
    category: 'profiles-frames',
    description: 'Equal angle 60x60mm, 6mm thickness',
    unlocksText: 'Frames, brackets, reinforcement',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 3400,
    leadTime: '2 days',
    leadTimeDays: 2,
    manufacturability: 98,
    specs: { width: 60, height: 60, wallThickness: 6, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint', 'Galvanized'],
  },
  {
    id: 'ang-004',
    name: 'Angle Iron 75x75x8mm',
    category: 'profiles-frames',
    description: 'Equal angle 75x75mm, 8mm thickness',
    unlocksText: 'Frames, brackets, reinforcement',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 4800,
    leadTime: '2 days',
    leadTimeDays: 2,
    manufacturability: 98,
    specs: { width: 75, height: 75, wallThickness: 8, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint', 'Galvanized'],
  },
  {
    id: 'ang-005',
    name: 'Angle Iron 25x25x3mm',
    category: 'profiles-frames',
    description: 'Equal angle 25x25mm, 3mm thickness',
    unlocksText: 'Frames, brackets, reinforcement',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 1200,
    leadTime: '2 days',
    leadTimeDays: 2,
    manufacturability: 98,
    specs: { width: 25, height: 25, wallThickness: 3, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint'],
  },
  {
    id: 'ang-006',
    name: 'Angle Iron 30x30x4mm',
    category: 'profiles-frames',
    description: 'Equal angle 30x30mm, 4mm thickness',
    unlocksText: 'Frames, brackets, reinforcement',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 1600,
    leadTime: '2 days',
    leadTimeDays: 2,
    manufacturability: 98,
    specs: { width: 30, height: 30, wallThickness: 4, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint'],
  },
  {
    id: 'ang-007',
    name: 'Angle Iron 80x80x10mm',
    category: 'profiles-frames',
    description: 'Equal angle 80x80mm, 10mm thickness',
    unlocksText: 'Frames, brackets, reinforcement',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 6200,
    leadTime: '3 days',
    leadTimeDays: 3,
    manufacturability: 98,
    specs: { width: 80, height: 80, wallThickness: 10, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint', 'Galvanized'],
  },
  {
    id: 'ang-008',
    name: 'Angle Iron 50x30x5mm',
    category: 'profiles-frames',
    description: 'Unequal angle 50x30mm, 5mm thickness',
    unlocksText: 'Frames, brackets, reinforcement',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 2400,
    leadTime: '2 days',
    leadTimeDays: 2,
    manufacturability: 98,
    specs: { width: 50, height: 30, wallThickness: 5, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint'],
  },
  {
    id: 'ang-009',
    name: 'Angle Iron 65x50x6mm',
    category: 'profiles-frames',
    description: 'Unequal angle 65x50mm, 6mm thickness',
    unlocksText: 'Frames, brackets, reinforcement',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 3200,
    leadTime: '2 days',
    leadTimeDays: 2,
    manufacturability: 98,
    specs: { width: 65, height: 50, wallThickness: 6, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint', 'Galvanized'],
  },
  {
    id: 'ang-010',
    name: 'Angle Iron 100x75x10mm',
    category: 'profiles-frames',
    description: 'Unequal angle 100x75mm, 10mm thickness',
    unlocksText: 'Frames, brackets, reinforcement',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 5800,
    leadTime: '3 days',
    leadTimeDays: 3,
    manufacturability: 98,
    specs: { width: 100, height: 75, wallThickness: 10, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint', 'Galvanized'],
  },

  // C-Channels (10)
  {
    id: 'cha-001',
    name: 'C-Channel 50x25x5mm',
    category: 'profiles-frames',
    description: 'C-channel 50x25mm, 5mm thickness',
    unlocksText: 'Structural frames, support beams',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 2600,
    leadTime: '3 days',
    leadTimeDays: 3,
    manufacturability: 97,
    specs: { width: 50, height: 25, wallThickness: 5, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint', 'Galvanized'],
  },
  {
    id: 'cha-002',
    name: 'C-Channel 75x40x6mm',
    category: 'profiles-frames',
    description: 'C-channel 75x40mm, 6mm thickness',
    unlocksText: 'Structural frames, support beams',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 3800,
    leadTime: '3 days',
    leadTimeDays: 3,
    manufacturability: 97,
    specs: { width: 75, height: 40, wallThickness: 6, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint', 'Galvanized'],
  },
  {
    id: 'cha-003',
    name: 'C-Channel 100x50x6mm',
    category: 'profiles-frames',
    description: 'C-channel 100x50mm, 6mm thickness',
    unlocksText: 'Structural frames, support beams',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 4800,
    leadTime: '3 days',
    leadTimeDays: 3,
    manufacturability: 97,
    specs: { width: 100, height: 50, wallThickness: 6, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint', 'Galvanized'],
  },
  {
    id: 'cha-004',
    name: 'C-Channel 120x60x7mm',
    category: 'profiles-frames',
    description: 'C-channel 120x60mm, 7mm thickness',
    unlocksText: 'Structural frames, support beams',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 6200,
    leadTime: '3 days',
    leadTimeDays: 3,
    manufacturability: 97,
    specs: { width: 120, height: 60, wallThickness: 7, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint', 'Galvanized'],
  },
  {
    id: 'cha-005',
    name: 'C-Channel 150x75x9mm',
    category: 'profiles-frames',
    description: 'C-channel 150x75mm, 9mm thickness',
    unlocksText: 'Structural frames, support beams',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 8500,
    leadTime: '4 days',
    leadTimeDays: 4,
    manufacturability: 97,
    specs: { width: 150, height: 75, wallThickness: 9, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint', 'Galvanized'],
  },
  {
    id: 'cha-006',
    name: 'C-Channel 40x20x4mm',
    category: 'profiles-frames',
    description: 'C-channel 40x20mm, 4mm thickness',
    unlocksText: 'Structural frames, support beams',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 1900,
    leadTime: '3 days',
    leadTimeDays: 3,
    manufacturability: 97,
    specs: { width: 40, height: 20, wallThickness: 4, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint'],
  },
  {
    id: 'cha-007',
    name: 'C-Channel 200x80x10mm',
    category: 'profiles-frames',
    description: 'C-channel 200x80mm, 10mm thickness',
    unlocksText: 'Structural frames, support beams',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 12000,
    leadTime: '4 days',
    leadTimeDays: 4,
    manufacturability: 97,
    specs: { width: 200, height: 80, wallThickness: 10, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint', 'Galvanized'],
  },
  {
    id: 'cha-008',
    name: 'C-Channel 65x35x5mm',
    category: 'profiles-frames',
    description: 'C-channel 65x35mm, 5mm thickness',
    unlocksText: 'Structural frames, support beams',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 3200,
    leadTime: '3 days',
    leadTimeDays: 3,
    manufacturability: 97,
    specs: { width: 65, height: 35, wallThickness: 5, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint'],
  },
  {
    id: 'cha-009',
    name: 'C-Channel 80x45x6mm',
    category: 'profiles-frames',
    description: 'C-channel 80x45mm, 6mm thickness',
    unlocksText: 'Structural frames, support beams',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 4100,
    leadTime: '3 days',
    leadTimeDays: 3,
    manufacturability: 97,
    specs: { width: 80, height: 45, wallThickness: 6, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint', 'Galvanized'],
  },
  {
    id: 'cha-010',
    name: 'C-Channel 30x15x3mm',
    category: 'profiles-frames',
    description: 'C-channel 30x15mm, 3mm thickness',
    unlocksText: 'Structural frames, support beams',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 1400,
    leadTime: '3 days',
    leadTimeDays: 3,
    manufacturability: 97,
    specs: { width: 30, height: 15, wallThickness: 3, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint'],
  },

  // I-Beam Minis (6)
  {
    id: 'ibm-001',
    name: 'I-Beam Mini 80x50x5mm',
    category: 'profiles-frames',
    description: 'Mini I-beam 80x50mm, 5mm web and flange',
    unlocksText: 'Heavy structural frames, load-bearing',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 4500,
    leadTime: '4 days',
    leadTimeDays: 4,
    manufacturability: 96,
    specs: { width: 80, height: 50, wallThickness: 5, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint', 'Galvanized'],
  },
  {
    id: 'ibm-002',
    name: 'I-Beam Mini 100x60x6mm',
    category: 'profiles-frames',
    description: 'Mini I-beam 100x60mm, 6mm web and flange',
    unlocksText: 'Heavy structural frames, load-bearing',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 5800,
    leadTime: '4 days',
    leadTimeDays: 4,
    manufacturability: 96,
    specs: { width: 100, height: 60, wallThickness: 6, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint', 'Galvanized'],
  },
  {
    id: 'ibm-003',
    name: 'I-Beam Mini 120x70x7mm',
    category: 'profiles-frames',
    description: 'Mini I-beam 120x70mm, 7mm web and flange',
    unlocksText: 'Heavy structural frames, load-bearing',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 7200,
    leadTime: '4 days',
    leadTimeDays: 4,
    manufacturability: 96,
    specs: { width: 120, height: 70, wallThickness: 7, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint', 'Galvanized'],
  },
  {
    id: 'ibm-004',
    name: 'I-Beam Mini 150x80x8mm',
    category: 'profiles-frames',
    description: 'Mini I-beam 150x80mm, 8mm web and flange',
    unlocksText: 'Heavy structural frames, load-bearing',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 9500,
    leadTime: '5 days',
    leadTimeDays: 5,
    manufacturability: 96,
    specs: { width: 150, height: 80, wallThickness: 8, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint', 'Galvanized'],
  },
  {
    id: 'ibm-005',
    name: 'I-Beam Mini 60x40x4mm',
    category: 'profiles-frames',
    description: 'Mini I-beam 60x40mm, 4mm web and flange',
    unlocksText: 'Heavy structural frames, load-bearing',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 3200,
    leadTime: '4 days',
    leadTimeDays: 4,
    manufacturability: 96,
    specs: { width: 60, height: 40, wallThickness: 4, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint'],
  },
  {
    id: 'ibm-006',
    name: 'I-Beam Mini 200x100x10mm',
    category: 'profiles-frames',
    description: 'Mini I-beam 200x100mm, 10mm web and flange',
    unlocksText: 'Heavy structural frames, load-bearing',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 14000,
    leadTime: '5 days',
    leadTimeDays: 5,
    manufacturability: 96,
    specs: { width: 200, height: 100, wallThickness: 10, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint', 'Galvanized'],
  },

  // T-Slots (Aluminum) (8)
  {
    id: 'tsl-001',
    name: 'T-Slot Aluminum 20x20mm',
    category: 'profiles-frames',
    description: 'Aluminum T-slot extrusion 20x20mm, modular system',
    unlocksText: 'Modular frames, machine enclosures, automation',
    material: 'Aluminum',
    process: 'Cut',
    finish: 'Anodize',
    basePrice: 2800,
    leadTime: '3 days',
    leadTimeDays: 3,
    manufacturability: 99,
    specs: { sideLength: 20, unitLength: 1000 },
    finishes: ['Anodize', 'Raw'],
  },
  {
    id: 'tsl-002',
    name: 'T-Slot Aluminum 30x30mm',
    category: 'profiles-frames',
    description: 'Aluminum T-slot extrusion 30x30mm, modular system',
    unlocksText: 'Modular frames, machine enclosures, automation',
    material: 'Aluminum',
    process: 'Cut',
    finish: 'Anodize',
    basePrice: 3600,
    leadTime: '3 days',
    leadTimeDays: 3,
    manufacturability: 99,
    specs: { sideLength: 30, unitLength: 1000 },
    finishes: ['Anodize', 'Raw'],
  },
  {
    id: 'tsl-003',
    name: 'T-Slot Aluminum 40x40mm',
    category: 'profiles-frames',
    description: 'Aluminum T-slot extrusion 40x40mm, modular system',
    unlocksText: 'Modular frames, machine enclosures, automation',
    material: 'Aluminum',
    process: 'Cut',
    finish: 'Anodize',
    basePrice: 4800,
    leadTime: '3 days',
    leadTimeDays: 3,
    manufacturability: 99,
    specs: { sideLength: 40, unitLength: 1000 },
    finishes: ['Anodize', 'Raw'],
  },
  {
    id: 'tsl-004',
    name: 'T-Slot Aluminum 45x45mm',
    category: 'profiles-frames',
    description: 'Aluminum T-slot extrusion 45x45mm, modular system',
    unlocksText: 'Modular frames, machine enclosures, automation',
    material: 'Aluminum',
    process: 'Cut',
    finish: 'Anodize',
    basePrice: 5500,
    leadTime: '3 days',
    leadTimeDays: 3,
    manufacturability: 99,
    specs: { sideLength: 45, unitLength: 1000 },
    finishes: ['Anodize', 'Raw'],
  },
  {
    id: 'tsl-005',
    name: 'T-Slot Aluminum 60x60mm',
    category: 'profiles-frames',
    description: 'Aluminum T-slot extrusion 60x60mm, heavy-duty modular',
    unlocksText: 'Modular frames, machine enclosures, automation',
    material: 'Aluminum',
    process: 'Cut',
    finish: 'Anodize',
    basePrice: 7800,
    leadTime: '3 days',
    leadTimeDays: 3,
    manufacturability: 99,
    specs: { sideLength: 60, unitLength: 1000 },
    finishes: ['Anodize', 'Raw'],
  },
  {
    id: 'tsl-006',
    name: 'T-Slot Aluminum 80x80mm',
    category: 'profiles-frames',
    description: 'Aluminum T-slot extrusion 80x80mm, extra heavy-duty',
    unlocksText: 'Modular frames, machine enclosures, automation',
    material: 'Aluminum',
    process: 'Cut',
    finish: 'Anodize',
    basePrice: 11500,
    leadTime: '4 days',
    leadTimeDays: 4,
    manufacturability: 99,
    specs: { sideLength: 80, unitLength: 1000 },
    finishes: ['Anodize', 'Raw'],
  },
  {
    id: 'tsl-007',
    name: 'T-Slot Aluminum 20x40mm',
    category: 'profiles-frames',
    description: 'Aluminum T-slot extrusion 20x40mm rectangular, modular',
    unlocksText: 'Modular frames, machine enclosures, automation',
    material: 'Aluminum',
    process: 'Cut',
    finish: 'Anodize',
    basePrice: 3200,
    leadTime: '3 days',
    leadTimeDays: 3,
    manufacturability: 99,
    specs: { width: 20, height: 40, unitLength: 1000 },
    finishes: ['Anodize', 'Raw'],
  },
  {
    id: 'tsl-008',
    name: 'T-Slot Aluminum 40x80mm',
    category: 'profiles-frames',
    description: 'Aluminum T-slot extrusion 40x80mm rectangular, heavy-duty',
    unlocksText: 'Modular frames, machine enclosures, automation',
    material: 'Aluminum',
    process: 'Cut',
    finish: 'Anodize',
    basePrice: 6800,
    leadTime: '3 days',
    leadTimeDays: 3,
    manufacturability: 99,
    specs: { width: 40, height: 80, unitLength: 1000 },
    finishes: ['Anodize', 'Raw'],
  },

  // Basalt Composite Beams (6)
  {
    id: 'bas-001',
    name: 'Basalt Composite Beam 50x50mm',
    category: 'profiles-frames',
    description:
      'Basalt fiber composite structural beam 50x50mm, lightweight and strong',
    unlocksText: 'Thermal-resistant frames, corrosion-proof structures',
    material: 'Basalt',
    process: 'Molded',
    finish: 'Raw',
    basePrice: 8500,
    leadTime: '7 days',
    leadTimeDays: 7,
    manufacturability: 93,
    specs: { sideLength: 50, unitLength: 1000 },
    finishes: ['Raw', 'Coating'],
  },
  {
    id: 'bas-002',
    name: 'Basalt Composite Beam 60x60mm',
    category: 'profiles-frames',
    description: 'Basalt fiber composite structural beam 60x60mm',
    unlocksText: 'Thermal-resistant frames, corrosion-proof structures',
    material: 'Basalt',
    process: 'Molded',
    finish: 'Raw',
    basePrice: 10500,
    leadTime: '7 days',
    leadTimeDays: 7,
    manufacturability: 93,
    specs: { sideLength: 60, unitLength: 1000 },
    finishes: ['Raw', 'Coating'],
  },
  {
    id: 'bas-003',
    name: 'Basalt Composite Beam 80x80mm',
    category: 'profiles-frames',
    description: 'Basalt fiber composite structural beam 80x80mm',
    unlocksText: 'Thermal-resistant frames, corrosion-proof structures',
    material: 'Basalt',
    process: 'Molded',
    finish: 'Raw',
    basePrice: 14500,
    leadTime: '7 days',
    leadTimeDays: 7,
    manufacturability: 93,
    specs: { sideLength: 80, unitLength: 1000 },
    finishes: ['Raw', 'Coating'],
  },
  {
    id: 'bas-004',
    name: 'Basalt Composite Beam 100x100mm',
    category: 'profiles-frames',
    description: 'Basalt fiber composite structural beam 100x100mm',
    unlocksText: 'Thermal-resistant frames, corrosion-proof structures',
    material: 'Basalt',
    process: 'Molded',
    finish: 'Raw',
    basePrice: 19500,
    leadTime: '7 days',
    leadTimeDays: 7,
    manufacturability: 93,
    specs: { sideLength: 100, unitLength: 1000 },
    finishes: ['Raw', 'Coating'],
  },
  {
    id: 'bas-005',
    name: 'Basalt Composite Beam 40x60mm',
    category: 'profiles-frames',
    description: 'Basalt fiber composite structural beam 40x60mm rectangular',
    unlocksText: 'Thermal-resistant frames, corrosion-proof structures',
    material: 'Basalt',
    process: 'Molded',
    finish: 'Raw',
    basePrice: 9500,
    leadTime: '7 days',
    leadTimeDays: 7,
    manufacturability: 93,
    specs: { width: 40, height: 60, unitLength: 1000 },
    finishes: ['Raw', 'Coating'],
  },
  {
    id: 'bas-006',
    name: 'Basalt Composite Beam 50x100mm',
    category: 'profiles-frames',
    description: 'Basalt fiber composite structural beam 50x100mm rectangular',
    unlocksText: 'Thermal-resistant frames, corrosion-proof structures',
    material: 'Basalt',
    process: 'Molded',
    finish: 'Raw',
    basePrice: 15500,
    leadTime: '7 days',
    leadTimeDays: 7,
    manufacturability: 93,
    specs: { width: 50, height: 100, unitLength: 1000 },
    finishes: ['Raw', 'Coating'],
  },

  // Flat Bars (10)
  {
    id: 'flb-001',
    name: 'Flat Bar 40x5mm',
    category: 'profiles-frames',
    description: 'Steel flat bar 40mm wide, 5mm thick',
    unlocksText: 'Brackets, reinforcement, structural supports',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 1800,
    leadTime: '2 days',
    leadTimeDays: 2,
    manufacturability: 99,
    specs: { width: 40, wallThickness: 5, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint', 'Galvanized'],
  },
  {
    id: 'flb-002',
    name: 'Flat Bar 50x6mm',
    category: 'profiles-frames',
    description: 'Steel flat bar 50mm wide, 6mm thick',
    unlocksText: 'Brackets, reinforcement, structural supports',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 2200,
    leadTime: '2 days',
    leadTimeDays: 2,
    manufacturability: 99,
    specs: { width: 50, wallThickness: 6, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint', 'Galvanized'],
  },
  {
    id: 'flb-003',
    name: 'Flat Bar 60x8mm',
    category: 'profiles-frames',
    description: 'Steel flat bar 60mm wide, 8mm thick',
    unlocksText: 'Brackets, reinforcement, structural supports',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 2900,
    leadTime: '2 days',
    leadTimeDays: 2,
    manufacturability: 99,
    specs: { width: 60, wallThickness: 8, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint', 'Galvanized'],
  },
  {
    id: 'flb-004',
    name: 'Flat Bar 80x10mm',
    category: 'profiles-frames',
    description: 'Steel flat bar 80mm wide, 10mm thick',
    unlocksText: 'Brackets, reinforcement, structural supports',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 4200,
    leadTime: '2 days',
    leadTimeDays: 2,
    manufacturability: 99,
    specs: { width: 80, wallThickness: 10, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint', 'Galvanized'],
  },
  {
    id: 'flb-005',
    name: 'Flat Bar 100x12mm',
    category: 'profiles-frames',
    description: 'Steel flat bar 100mm wide, 12mm thick',
    unlocksText: 'Brackets, reinforcement, structural supports',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 5800,
    leadTime: '3 days',
    leadTimeDays: 3,
    manufacturability: 99,
    specs: { width: 100, wallThickness: 12, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint', 'Galvanized'],
  },
  {
    id: 'flb-006',
    name: 'Flat Bar 25x3mm',
    category: 'profiles-frames',
    description: 'Steel flat bar 25mm wide, 3mm thick',
    unlocksText: 'Brackets, reinforcement, structural supports',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 1200,
    leadTime: '2 days',
    leadTimeDays: 2,
    manufacturability: 99,
    specs: { width: 25, wallThickness: 3, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint'],
  },
  {
    id: 'flb-007',
    name: 'Flat Bar 30x4mm',
    category: 'profiles-frames',
    description: 'Steel flat bar 30mm wide, 4mm thick',
    unlocksText: 'Brackets, reinforcement, structural supports',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 1500,
    leadTime: '2 days',
    leadTimeDays: 2,
    manufacturability: 99,
    specs: { width: 30, wallThickness: 4, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint'],
  },
  {
    id: 'flb-008',
    name: 'Flat Bar 120x15mm',
    category: 'profiles-frames',
    description: 'Steel flat bar 120mm wide, 15mm thick',
    unlocksText: 'Brackets, reinforcement, structural supports',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 8500,
    leadTime: '3 days',
    leadTimeDays: 3,
    manufacturability: 99,
    specs: { width: 120, wallThickness: 15, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint', 'Galvanized'],
  },
  {
    id: 'flb-009',
    name: 'Flat Bar 20x2mm',
    category: 'profiles-frames',
    description: 'Steel flat bar 20mm wide, 2mm thick',
    unlocksText: 'Brackets, reinforcement, structural supports',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 900,
    leadTime: '2 days',
    leadTimeDays: 2,
    manufacturability: 99,
    specs: { width: 20, wallThickness: 2, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint'],
  },
  {
    id: 'flb-010',
    name: 'Flat Bar 150x20mm',
    category: 'profiles-frames',
    description: 'Steel flat bar 150mm wide, 20mm thick',
    unlocksText: 'Brackets, reinforcement, structural supports',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 12000,
    leadTime: '3 days',
    leadTimeDays: 3,
    manufacturability: 99,
    specs: { width: 150, wallThickness: 20, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint', 'Galvanized'],
  },

  // Pipe Sections (10)
  {
    id: 'pip-001',
    name: 'Round Pipe 25mm OD x 2mm Wall',
    category: 'profiles-frames',
    description: 'Round steel pipe 25mm outside diameter, 2mm wall',
    unlocksText: 'Fluid systems, structural frames, handles',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 1600,
    leadTime: '2 days',
    leadTimeDays: 2,
    manufacturability: 98,
    specs: { diameter: 25, wallThickness: 2, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint', 'Galvanized'],
  },
  {
    id: 'pip-002',
    name: 'Round Pipe 32mm OD x 2.5mm Wall',
    category: 'profiles-frames',
    description: 'Round steel pipe 32mm outside diameter, 2.5mm wall',
    unlocksText: 'Fluid systems, structural frames, handles',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 2000,
    leadTime: '2 days',
    leadTimeDays: 2,
    manufacturability: 98,
    specs: { diameter: 32, wallThickness: 2.5, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint', 'Galvanized'],
  },
  {
    id: 'pip-003',
    name: 'Round Pipe 40mm OD x 3mm Wall',
    category: 'profiles-frames',
    description: 'Round steel pipe 40mm outside diameter, 3mm wall',
    unlocksText: 'Fluid systems, structural frames, handles',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 2600,
    leadTime: '2 days',
    leadTimeDays: 2,
    manufacturability: 98,
    specs: { diameter: 40, wallThickness: 3, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint', 'Galvanized'],
  },
  {
    id: 'pip-004',
    name: 'Round Pipe 50mm OD x 3mm Wall',
    category: 'profiles-frames',
    description: 'Round steel pipe 50mm outside diameter, 3mm wall',
    unlocksText: 'Fluid systems, structural frames, handles',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 3200,
    leadTime: '2 days',
    leadTimeDays: 2,
    manufacturability: 98,
    specs: { diameter: 50, wallThickness: 3, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint', 'Galvanized'],
  },
  {
    id: 'pip-005',
    name: 'Round Pipe 60mm OD x 4mm Wall',
    category: 'profiles-frames',
    description: 'Round steel pipe 60mm outside diameter, 4mm wall',
    unlocksText: 'Fluid systems, structural frames, handles',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 4200,
    leadTime: '3 days',
    leadTimeDays: 3,
    manufacturability: 98,
    specs: { diameter: 60, wallThickness: 4, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint', 'Galvanized'],
  },
  {
    id: 'pip-006',
    name: 'Round Pipe 76mm OD x 5mm Wall',
    category: 'profiles-frames',
    description: 'Round steel pipe 76mm outside diameter, 5mm wall',
    unlocksText: 'Fluid systems, structural frames, handles',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 5800,
    leadTime: '3 days',
    leadTimeDays: 3,
    manufacturability: 98,
    specs: { diameter: 76, wallThickness: 5, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint', 'Galvanized'],
  },
  {
    id: 'pip-007',
    name: 'Round Pipe 20mm OD x 2mm Wall',
    category: 'profiles-frames',
    description: 'Round steel pipe 20mm outside diameter, 2mm wall',
    unlocksText: 'Fluid systems, structural frames, handles',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 1300,
    leadTime: '2 days',
    leadTimeDays: 2,
    manufacturability: 98,
    specs: { diameter: 20, wallThickness: 2, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint'],
  },
  {
    id: 'pip-008',
    name: 'Round Pipe 89mm OD x 6mm Wall',
    category: 'profiles-frames',
    description: 'Round steel pipe 89mm outside diameter, 6mm wall',
    unlocksText: 'Fluid systems, structural frames, handles',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 7200,
    leadTime: '3 days',
    leadTimeDays: 3,
    manufacturability: 98,
    specs: { diameter: 89, wallThickness: 6, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint', 'Galvanized'],
  },
  {
    id: 'pip-009',
    name: 'Round Pipe 100mm OD x 6mm Wall',
    category: 'profiles-frames',
    description: 'Round steel pipe 100mm outside diameter, 6mm wall',
    unlocksText: 'Fluid systems, structural frames, handles',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 8500,
    leadTime: '3 days',
    leadTimeDays: 3,
    manufacturability: 98,
    specs: { diameter: 100, wallThickness: 6, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint', 'Galvanized'],
  },
  {
    id: 'pip-010',
    name: 'Round Pipe 15mm OD x 1.5mm Wall',
    category: 'profiles-frames',
    description: 'Round steel pipe 15mm outside diameter, 1.5mm wall',
    unlocksText: 'Fluid systems, structural frames, handles',
    material: 'Steel',
    process: 'Cut',
    finish: 'Raw',
    basePrice: 1000,
    leadTime: '2 days',
    leadTimeDays: 2,
    manufacturability: 98,
    specs: { diameter: 15, wallThickness: 1.5, unitLength: 1000 },
    finishes: ['Raw', 'Powder Coat', 'Paint'],
  },
];

// Import generated parts
import {
  generatePlatesSheets,
  generateFasteners,
  generateBearingsShafts,
  generatePowerTransmission,
  generateEnclosures,
  generateFluidProcess,
  generateThermal,
  generateMobility,
  generateElectricalIoT,
  generateTooling,
} from './generate-catalog-parts';

// Combine all parts (465 total)
export const CATALOG_PARTS: CatalogPart[] = [
  ...structuralProfiles, // 80 parts
  ...generatePlatesSheets(), // 60 parts
  ...generateFasteners(), // 70 parts
  ...generateBearingsShafts(), // 50 parts
  ...generatePowerTransmission(), // 45 parts
  ...generateEnclosures(), // 40 parts
  ...generateFluidProcess(), // 45 parts
  ...generateThermal(), // 30 parts
  ...generateMobility(), // 30 parts
  ...generateElectricalIoT(), // 25 parts
  ...generateTooling(), // 25 parts
];

// Helper functions
export function getCategoryById(id: CategoryId): CatalogCategory | undefined {
  return CATALOG_CATEGORIES.find((cat) => cat.id === id);
}

export function getPartsByCategory(categoryId: CategoryId): CatalogPart[] {
  return CATALOG_PARTS.filter((part) => part.category === categoryId);
}

export function getAllCategories(): CatalogCategory[] {
  return CATALOG_CATEGORIES;
}

export function searchParts(query: string): CatalogPart[] {
  const lowerQuery = query.toLowerCase();
  return CATALOG_PARTS.filter(
    (part) =>
      part.name.toLowerCase().includes(lowerQuery) ||
      part.description.toLowerCase().includes(lowerQuery) ||
      part.unlocksText.toLowerCase().includes(lowerQuery),
  );
}

export function filterParts(filters: {
  category?: CategoryId;
  materials?: string[];
  processes?: string[];
  finishes?: string[];
  minPrice?: number;
  maxPrice?: number;
}): CatalogPart[] {
  let filtered = [...CATALOG_PARTS];

  if (filters.category) {
    filtered = filtered.filter((part) => part.category === filters.category);
  }

  if (filters.materials && filters.materials.length > 0) {
    filtered = filtered.filter((part) =>
      filters.materials!.includes(part.material),
    );
  }

  if (filters.processes && filters.processes.length > 0) {
    filtered = filtered.filter(
      (part) => part.process && filters.processes!.includes(part.process),
    );
  }

  if (filters.finishes && filters.finishes.length > 0) {
    filtered = filtered.filter(
      (part) => part.finish && filters.finishes!.includes(part.finish),
    );
  }

  if (filters.minPrice !== undefined && filters.maxPrice !== undefined) {
    filtered = filtered.filter(
      (part) =>
        part.basePrice >= filters.minPrice! &&
        part.basePrice <= filters.maxPrice!,
    );
  }

  return filtered;
}
